# --------------------------------------
#               插件配置
# --------------------------------------
# 配置文件版本
version: 1.3.0
# 检查更新开关,关闭后将禁用插件启用时的更新检查,只能通过/boom update查询插件更新
update: true

# --------------------------------------
#               爆炸相关
# --------------------------------------
# 配置阻止对应事件的世界,世界名字区分大小写,设置为空则禁用该功能
# 空列表示例,下面接一个空列表项即为空,如果不接一个空列表项则会使用默认配置文件
# example:
#   -
# 或者 (注意冒号后面有空格)
# example: {}
explosion:
  # 阻止苦力怕的爆炸破坏方块,阻止后有伤害
  CREEPER:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止苦力怕爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止苦力怕爆炸后是否生成音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止TNT的爆炸破坏方块,阻止后有伤害
  PRIMED_TNT:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止TNT爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止TNT爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止末影水晶的爆炸,阻止后无伤害
  ENDER_CRYSTAL:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止末影水晶爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止末影水晶爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止凋灵出生的爆炸破坏方块,阻止后有伤害
  WITHER:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止凋灵出生爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止凋灵出生爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止凋灵头颅的爆炸破坏方块,阻止后有伤害
  WITHER_SKULL:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止凋灵头颅爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止凋灵头颅爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止恶魂火球的爆炸破坏方块,阻止后有伤害
  FIREBALL:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止恶魂火球爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止恶魂火球爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

  # 阻止TNT矿车的爆炸破坏方块,阻止后有伤害
  MINECART_TNT:
    # 阻止的世界列表,可自行添加,设置为空则禁用该功能
    world:
      - world
      - world_nether
      - world_the_end
    # 阻止TNT矿车爆炸后是否生成爆炸粒子（爆炸的特效）,开启不会破坏地形
    particle: true
    # 阻止TNT矿车爆炸后是否生成爆炸音效
    sound: true
    # 设置为true将会阻止爆炸对掉落物造成伤害
    item-damage: true
    # 设置为true将会阻止爆炸对玩家造成伤害
    player-damage: false
    # 设置为true将会阻止爆炸对其他实体(不包括掉落物和玩家)造成伤害
    other-damage: false

# --------------------------------------
#              火焰相关
# --------------------------------------
fire:
  # 阻止火焰蔓延及烧毁方块的世界,可自行添加
  world:
    - world
    - world_nether
    - world_the_end
  # 阻止的火焰蔓延原因
  # 不在上方的世界列表中的世界不会被检测
  # 加到下方ignite列表中的原因将会被检测并禁止
  # 此列表为空时所有方块被点燃均不会被阻止
  # ARROW - 火矢引起的着火。
  # ENDER_CRYSTAL - 末影水晶爆炸生成的火焰
  # EXPLOSION - 爆炸生成的火焰
  # FIREBALL - 火球生成的火焰
  # FLINT_AND_STEEL - 打火石生成的火焰
  # LAVA - 岩浆生成的火焰
  # LIGHTNING - 雷电生成的火焰
  # SPREAD - 蔓延生成的火焰
  ignite:
    - SPREAD
    - LIGHTNING
    - LAVA

# --------------------------------------
#              耕地保护
# --------------------------------------
farmland:
  # 启用农田保护的世界列表,可自行添加
  world:
    - world
    - world_the_end

# --------------------------------------
#              实体转换
# --------------------------------------
transform:
  # 阻止苦力怕被雷击后变成高压苦力怕
  CREEPER:
    # 启用的世界列表,可自行添加
    world:
      - world
      - world_nether
      - world_the_end
  # 阻止村民被雷击之后变成女巫
  VILLAGER:
    # 启用的世界列表,可自行添加
    world:
      - world
      - world_nether
      - world_the_end
  # 阻止僵尸村民被治愈
  ZOMBIE_VILLAGER:
    # 启用的世界列表,可自行添加
    world:
    # - world
    # - world_nether
    # - world_the_end
  # 阻止猪灵在非下界世界中变成僵尸猪灵
  PIGLIN:
    # 启用的世界列表,可自行添加
    world:
      - world
      - world_the_end
  # 阻止猪灵蛮兵在非下界世界中变成僵尸猪灵
  PIGLIN_BRUTE:
    # 启用的世界列表,可自行添加
    world:
      - world
      - world_the_end
  # 阻止疣猪兽在非下界世界中变成僵尸疣猪兽
  HOGLIN:
    # 启用的世界列表,可自行添加
    world:
      - world
      - world_the_end
  # 阻止僵尸变成溺尸
  ZOMBIE:
    # 启用的世界列表,可自行添加
    world:
    # - world
    # - world_the_end

# --------------------------------------
#              末影人相关
# --------------------------------------
enderman:
  # 阻止末影人搬起方块的世界,可自行添加
  world:
    - world
    # - world_nether
    # - world_the_end

# --------------------------------------
#               床相关
# --------------------------------------
# 非主世界使用床会爆炸
bed:
  # 阻止床的使用的世界,可自行添加
  world:
    - world_nether
    - world_the_end
  # 阻止使用床时返回的消息,设置为 "" 以禁用
  message: "&c该世界不能使用床"
  # 阻止时发出的音效,设置为空以禁用,可用音效列表 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sound: "ENTITY_VILLAGER_NO"
  particle:
    # 阻止时在床上显示的粒子效果,设置为空以禁用,可用粒子列表 https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
    type: "REDSTONE"
    # 阻止时显示的粒子的数量
    count: 20
    # 阻止时显示的粒子的偏移（x轴,y轴,z轴）
    move: [ 0.5,1.0,0.5 ]
    # 阻止时显示的粒子的扩散范围（x轴,y轴,z轴）
    offset: [ 0.1,0.1,0.1 ]
    # 阻止时显示的粒子颜色（输入rgb值）（只有粒子为REDSTONE时才可用）（白色为 255 / 255 / 255）
    color: [ 255,50,50 ]
    # 阻止时显示的粒子大小（只有粒子为REDSTONE时才可用）
    size: 2

# --------------------------------------
#              重生锚相关
# --------------------------------------
# 非主世界使用重生锚会爆炸
# 阻止使用重生锚（不影响充能,只阻止绑定）
respawn-anchor:
  # 阻止使用重生锚的世界,可自行添加
  world:
    - world
    - world_the_end
  # 阻止使用重生锚时返回的消息,设置为 "" 以禁用
  message: "&c该世界不能使用重生锚"
  # 阻止时发出的音效,设置为空以禁用,可用音效列表 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sound: "ENTITY_VILLAGER_NO"
  particle:
    # 阻止时显示在重生锚上的粒子效果,设置为空以禁用,可用粒子列表 https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
    type: "REDSTONE"
    # 阻止时显示的粒子的数量
    count: 20
    # 阻止时显示的粒子的偏移（x轴,y轴,z轴）
    move: [ 0.5,1.0,0.5 ]
    # 阻止时显示的粒子的扩散范围（x轴,y轴,z轴）
    offset: [ 0.1,0.1,0.1 ]
    # 阻止时显示的粒子颜色（输入rgb值）（只有粒子为REDSTONE时才可用）（白色为 255 / 255 / 255）
    color: [ 255,50,50 ]
    # 阻止时显示的粒子大小（只有粒子为REDSTONE时才可用）
    size: 2

# --------------------------------------
#              禁用指令
# --------------------------------------
disable-command:
  # OP默认跳过本检测
  # 在本模块中{player}为玩家名字，{command}为玩家使用的禁止指令,{ip}为玩家的ip地址
  message:
    # 当玩家输入禁用列表中的指令时,返回给玩家指定的消息,可以是输入未知指令的样式,也可以是自定义的字符串,支持颜色代码,特殊字符请用\转义
    user: "&fUnknown command. Type \"/help\" for help."
    # 当玩家输入禁用列表中的指令时,会在后台返回指定的消息尝试使用的指令,支持颜色代码,留空以禁用后台消息
    console: "&c{player}&f尝试使用指令&c{command}"
    # 当玩家输入禁用列表中的指令时,发送给op的消息，支持颜色代码，留空以禁用,禁用的同时会禁用音效
    op: "&c{player}&f尝试使用指令&c{command}"

  # 玩家使用禁用指令后控制台执行的指令
  # 设置为空列表以禁用该功能,示例如下
  # command-trigger: []
  # 或
  # command-trigger:
  #   -
  command-trigger:
    -
      #- "say {player} 使用了禁用指令 {command}, ip地址{ip}"
      #- "kick {player} 使用了禁用指令"

      # 当玩家输入禁用列表中的指令时,发送给op的音效,设置为空以禁用
    # 可用音效列表 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  op-sound: "BLOCK_ANVIL_LAND"

  # 记录日志
  log:
    # 是否将玩家使用禁止指令记入到log文件中，设置为true以启用
    enable: true
    # 将玩家使用禁止指令记入到log文件中使用的时间格式，不支持颜色代码,格式参考 http://www.foxtable.com/webhelp/topics/0362.htm
    datetime-format: "[yyyy.MM.dd HH:mm:ss]"
    # 将玩家使用禁止指令记入到log文件中使用的格式，不支持颜色代码
    log-format: "{player}: {command} (IP: {ip})"
    # log的文件名，不可为空
    file: "record.log"

  # 在下面输入你要阻止玩家使用的指令
  # 有boom.commandbypass权限的玩家可以跳过此检查
  # 下方的指令转接可以跳过此限制
  # 必须是小写! 不需要带/!
  # 设置为空以禁用
  # 无前缀需要指令完全匹配(无视大小写)
  # @前缀需要指令主命令完全匹配(主命令是指令按空格分段的第一段,比如'/pl a'的主命令就是 pl)
  # $前缀只需要指令主命令包含此字符串
  #
  # 全局禁用指令
  commands:
    - "@pl"
    - "@plugins"
    - "@ver"
    - "@version"
    - "$?"
    - "$bukkit:"
  #    - "$boom"

  # 按世界禁用指令
  # 支持@和$前缀
  worlds:
    # 世界名字
    world:
      - "papi"
      - "在下方自行添加"
    world_nether:
      - "你要在world_nether世界中禁用的指令"
      - "在下方自行添加"
    其他要禁用指令的世界: []

# --------------------------------------
#                指令转接
# --------------------------------------
#   !!! 所有项目在这儿请用小写 !!!
# 玩家使用指令转接的日志格式,设置为空以禁用,{player}指代玩家，{pic}指代玩家输入的指令,{pec}指代转接后玩家执行的指令
# 需要权限boom.transfer.*
# 或者boom.transfer.指令名字
transfer-command:
  info: "&2{player}输入{pic}转接执行了{pec}"
  # 在此以playerInputCommand-PlayerExecuteCommand(输入的指令-转接执行指令)的方式写你要转接的命令，不需要/  (worldedit的指令需要带一个/)
  # 可以用转接指令转接禁用的指令
  # 让玩家只能使用playerInputCommand
  # 转接指令没有tab补全
  list:
    - tpok-tpaccept
    - tpyes-tpaccept

# --------------------------------------
#                指令简化
# --------------------------------------
# 可以用一条指令执行多条指令
# 自动跳过禁用指令的检查
# 需要权限boom.easy.*
# 或者boom.easy.指令名字
easy-command:
  # 在此处写你要使用的简化指令
  eazy_hello:
    - "say 呦"
    - "say 今天天气真不错"

# --------------------------------------
#              控制实体生成
# --------------------------------------
#   !!! 所有项目在这儿请用小写 !!!
# 生物生成的几率数值设置范围为0-100,不需要%,设置为0或者更小视为禁用刷新,超过100视为不做限制
disable-spawn-entity:
  # 要限制刷怪的世界名称,可自行添加
  world_example:
    # 添加的刷怪限制的格式为 实体名字: 刷新几率
    # 刷新几率必须为数字,且不需要引号""
    # 如果几率写100虽然不会限制刷怪，但是会占用一定的性能
    bat: 0 # 这将会禁用example_world世界的蝙蝠生成(0%)
    zombified_piglin: 25 # 这将会使僵尸猪灵在example_world世界的生成概率为原版概率的25%
#  world:
#    bat: 0